### ISSUE TITLE
FN: should have triggered on funding of malicious account

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#236]
Tx mainnet: 0x3310f2f45bb6d2d1e96a1d737d50e287f5976367a693f1b5cc172e470c874a0e

**Comment by 0xtaf** [comment]
@christian-forta 
for malicious account funding, this tx’s label api results are these
[https://api.forta.network/labels/state?entities=0x00001f78189be22c3498cff1b8e02272c32[…]0&sourceIds=etherscan&labels=*xploit*,*hish*,*heist*&limit=1](https://api.forta.network/labels/state?entities=0x00001f78189be22c3498cff1b8e02272c3220000&sourceIds=etherscan&labels=*xploit*,*hish*,*heist*&limit=1)

[https://api.forta.network/labels/state?entities=0x00001f78189be22c3498cff1b8e02272c32[…]rceIds=etherscan-tags&labels=*xploit*,*hish*,*heist*&limit=1](https://api.forta.network/labels/state?entities=0x00001f78189be22c3498cff1b8e02272c3220000&sourceIds=etherscan-tags&labels=*xploit*,*hish*,*heist*&limit=1)


it doesn’t create an alert because label api returns empty for the drainer address. how do you want to proceed?

**Comment by christian-forta** [comment]
https://app.forta.network/bot/0x2df302b07030b5ff8a17c91f36b08f9e2b1e54853094e2513f7cda734cf68a46

1. Change the label check to use get_labels from scam detector
2. Move away from Forta label/state? URL to use Etherscan's label API

**Comment by christian-forta** [comment]
this is fixed and deployed
