### ISSUE TITLE
FN: No FLD_FUNDING alert for new account funding 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#295]
Optimism bridge funding
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Tx  - https://optimistic.etherscan.io/tx/0xd6e7ce4f95384762bcf36b04c05929e1fb75d46f8acbc48615b89baf1be7f6a4

https://optimistic.etherscan.io/tx/0xe0d8116ada9d6c58896dc326cd82f8d48ced30962c2f8ef6712c400fc096c234

**Comment by christian-forta** [comment]
@0xtaf  - any update on this?

**Comment by 0xtaf** [comment]
@christian-forta , since this is a bridge transaction between L1-L2, `from` and `to` addresses are L1 and L2 messengers. the bot currently assumes either `from` or `to` is an EOA either getting funded or laundering money. that's the reason of this FN. I'm thinking of a solution for this. maybe I'll add another condition using these L1-L2 bridging events like `DepositFinalized`

**Comment by christian-forta** [comment]
We do have the L1 funding alert: https://explorer.forta.network/alert/0x64693d9f1565375aa9bbd869f14803e2defd39ec7b8e0a288c3403a7053f4c39

This is not an FN.
