### ISSUE TITLE
No FLD_NEW_FUNDING alert for new account funding

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#330]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058

Funding tx - https://bscscan.com/tx/0x2a3366501b7412cb92e2eba4ae91fd5e74dd4c7ebb93b0007593f416982013ce

**Comment by 0xtaf** [comment]
seems like the bot hasn't been receiving transactions in Ethereum and BSC nodes

**Comment by christian-forta** [comment]
nor sure what you mean by that?

**Comment by christian-forta** [comment]
Yes, that is interesting. Could you pls reach out to the dev team to
understand whats going on?

**Comment by 0xtaf** [comment]
the node issue is fixed but this issue is still valid.

my conclusion: the bot currently checks for native transfers and ERC20 transfers. this tx is a Tornado Cash withdrawal and it doesn't emit a Transfer event. because of that, the bot misses these type of txns.

Withdrawal event emission will also be added.

**Comment by 0xtaf** [comment]
TC funding didn't trigger but it triggers locally. 

![image](https://github.com/forta-network/starter-kits/assets/25147738/7703593b-c7a5-4541-9084-b7fda7e43893)

**Comment by christian-forta** [comment]
drop rate on TC bot were high in Aug; no longer an issue. As such, funding (TC) should be emitted. Closing as 'no issue'
