### ISSUE TITLE
FP ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#375]
There seem to be an issue in some ice phsihing cases. The base bot that is making the scam detector trigger, seems to be associated with address poisoning.

e.g: [Alert](https://app.forta.network/alerts/0x1d8d15d752cb98bf5633dfaf94c501a720032ccc0922e41154ca7e10ef6d3aa4)
e.2: [Alert](https://app.forta.network/alerts/0xabac60ee670e49c78dd3fbc6fbe67e7d4ee74de26507cb9a6c9e3dadfcdc7e0c)

**Comment by Vxatz** [comment]
@christian-forta , could you have a look at these?

Is it related to the ML model? Locally, I get only Address Poisoning passthrough alerts

**Comment by Vxatz** [comment]
@christian-forta , looking at it again, I believe it's related to the `FINDINGS_CACHE_ALERT`. Since we permit a maximum number of alerts to be triggered per `handle_alert` call, some alerts will be fired during the subsequent alert resulting in a different "source alert" (The metadata still contains the correct info, though)

This could also happen with the `FINDINGS_CACHE_BLOCK` with the block number of the SD alert being different from the one of the source.

**Comment by christian-forta** [comment]
Yes, this is an architectual issue. We could ask the dev team to see whether a bot should be allowed to set the source alert directly citing this as an example. 

But given the metadata is correct, I would say its lower pri. 

Now, that said, where is the FP coming from the ML model. @salort-forta , could you take a look?
