### ISSUE TITLE
Add contract deployed by initiator to large profit base bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#531]
Attacker - [0xe311bfd4ce91a5c3f600a8f235111003c7d6f987](https://etherscan.io/address/0xe311bfd4ce91a5c3f600a8f235111003c7d6f987)
AD alert - https://app.forta.network/alerts/0x908dce70ea6cbb10d2d70a3d8125bbd52aaa82df067e07589459d4a566b3352a
Base bots - [SUSPICIOUS-CONTRACT-CREATION](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99) and [LARGE-PROFIT](https://app.forta.network/bot/0xb4c76a09b9fb81eeb87945144b56c4652a476206248d8ee53902e80c96ebf14d)
Potential cause -  large profit wasn't made by the initiator(FP by large profit bot)

Similar alerts 
LARGE-PROFIT - FP
attacker - 0x30bdece54caf56d5035ea521d56b48c47f10c216 (https://etherscan.io/address/0x30bdece54caf56d5035ea521d56b48c47f10c216)
AD alert - https://app.forta.network/alerts/0xb46f7c6c22855a26809906ef7fcb08aceb7ede1810f88eff186117074b86763c
Reason - No profit for the initiator in the [tx](https://app.forta.network/alerts/0xb46f7c6c22855a26809906ef7fcb08aceb7ede1810f88eff186117074b86763c) 

 LARGE-PROFIT - FP
attacker - 0x5acbef8a8a7a8c3b29f15498c8e682bbf22eab43 (https://bscscan.com/address/0x5acbef8a8a7a8c3b29f15498c8e682bbf22eab43)
AD alert - https://app.forta.network/alerts/0x347f732409bce196cb152d4009eb7e1ce9f387f10b3d1527ecbacf4c2b4b5210
Reason - [FP](https://app.forta.network/alerts/0x557ebda621cab5a980394ce9d270c4733d2415aeee9f19091fd3a79522c572ae) by large profit bot. Tx Initiator didn't make a large profit.

**Comment by Vxatz** [comment]
Hey @Olugbenga2000, regarding the first issue, we're also considering contracts deployed by the tx initiator as part of the initiator's profit. (I believe eUSD is a stablecoin, so that must be +14k for the called contract)

The 2nd has been fixed since the last update of the bot (Feb 9).

The 3rd is strange. I'm guessing it could be due to a stale token price fetched (Can't repro locally)
In the last bot update, I have added the profit address to the metadata, so it will be more clear going forward.

**Comment by Thisisgeorg3** [comment]
@Vxatz , lets add the contracts deployed by txn initiator 
@Ivan1905 FYI to keep in mind for potential future FPs

Going to update this ticket

**Comment by Vxatz** [comment]
Hi @Thisisgeorg3, the bot is already considering those contracts (hence the alert above)
