### ISSUE TITLE
FN entity clustering - Rugged art

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#573]
In the recent [rugged art attack](https://x.com/rugged_dot_art/status/1760597634623086816?s=20)

The address was funded through TC and then transferred to another address that eventually deployed the malicious smart contract.

Funded address: https://etherscan.io/address/0x575d4871cf7e9214fb705a440f1ea99624690fb3#internaltx
Malicious address that deployed the contract: https://etherscan.io/address/0x9733303117504c146A4E22261F2685ddb79780eF

I am seeing that only the beta one alerted, here the [alert](https://app.forta.network/alerts/0x861786b407302723091857e235c705a556f5033c6312a402b551f7e2cc62fe33) - While checking the metadata I am not seeing any alert referring to funding although there are [funding alerts ](https://app.forta.network/alerts?addresses=0x575D4871cf7E9214fB705a440f1eA99624690fB3&limit=15&sort=desc)

My question is: does the entity clustering logic working properly?

**Comment by Vxatz** [comment]
The issue was that it wasn't the first but the second tx of the funded address and that's why it wasn't considered a "new account".

I have adjusted the threshold in this [PR](https://github.com/forta-network/starter-kits/pull/586/files) to permit one additional transaction while still recognizing it as new.

In the future, we could update the threshold even more if necessary.
