### ISSUE TITLE
Large profit - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#583]
https://app.forta.network/alerts/0x6af3208776ba05da6e3e52842e17f783c3c362525e5d41226667c21f74a28532
potential cause - Alert for a swap tx (uniswap)

**Comment by Vxatz** [comment]
Direct Uniswap V2 swaps are already excluded. In this case, there was a call to a contract created by the initiator which then called Uniswap. In these cases I would suggest against filtering out internal swaps.

However, there is another check in the bot (to look for more than 3 Transfer events in the tx), which was exceeded (4  transfer events in the tx) because one of the events was a self-transfer. This has now been fixed in https://github.com/NethermindEth/Forta-Agents/pull/473.
